service: serverless-example

plugins:
  - alliants-serverless-utils/plugins/bundle
  - alliants-serverless-utils/plugins/documentation
  - alliants-serverless-utils/plugins/bruno
  - alliants-serverless-utils/plugins/offline-sqs
  - serverless-offline

package:
  individually: true
  patterns:
    - static/global.txt

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, '${env:stage, "dev"}'}

custom:
  documentation:
    schemasPath: src/schemas/schemas.js
    errorsPath: src/utils/errors.js
    version: "1"
    title: Example API
    description: OpenAPI documentation.
  serverless-offline-sqs: # Visit http://localhost:9324/?Action=ListQueues locally to list queues
    autoCreate: true
    apiVersion: 2012-11-05
    endpoint: http://localhost:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
  queues:
    test-queue:
      queueName: test_queue
      dlqQueueName: dlq_test_queue

functions:
  hello1:
    handler: src/handlers/hello1.handler
    package:
      patterns:
        - static/individual.txt
    events:
      - http:
          path: hello1
          method: get

  hello2:
    handler: src/handlers/hello2.handler
    events:
      - http:
          path: hello2/{name}
          method: get

  hello3:
    handler: src/handlers/hello3.handler
    events:
      - http:
          path: hello3
          method: post
